### ISSUE TITLE
Fails to build with GHC 9.0.1

### ISSUE THREAD

**Issue by vmchale** [codedownio/aeson-typescript#25]
```
[7 of 9] Compiling Data.Aeson.TypeScript.TH ( src/Data/Aeson/TypeScript/TH.hs, /tmp/aeson-typescript-0.3.0.0/dist-newstyle/build/x86_64-linux/ghc-9.0.1/aeson-typescript-0.3.0.0/build/Data/Aeson/TypeScript/TH.o, /tmp/aeson-typescript-0.3.0.0/dist-newstyle/build/x86_64-linux/ghc-9.0.1/aeson-typescript-0.3.0.0/build/Data/Aeson/TypeScript/TH.dyn_o )

src/Data/Aeson/TypeScript/TH.hs:315:37: error:
    • Couldn't match expected type: TyVarBndr ()
                  with actual type: flag0 -> TyVarBndr flag0
    • Probable cause: ‘PlainTV’ is applied to too few arguments
      In the expression: PlainTV f
      In the third argument of ‘DataD’, namely ‘[PlainTV f]’
      In the expression: DataD [] name' [PlainTV f] Nothing [] []
    |
315 |         let inst1 = DataD [] name' [PlainTV f] Nothing [] []
    |                                     ^^^^^^^^^
```

**Comment by thomasjm** [comment]
Fixed in 2c8bb13c2f46eba912ec8bb0cb67f553bc4a986c and released as [0.3.0.1](https://hackage.haskell.org/package/aeson-typescript-0.3.0.1) -- thanks for the report!
